ssbc/async-append-only-log

- README.md
Some minor typos and some (hopefully clearer) formulations.
> small README fixes

- index.js
- package.json
- stream.js
10x (well, honestly 8.5x) improvement in performance. Pair programmed with @arj03
> replace setImmediate with looper

- index.js
Before when you were waiting for drain you would just be called whenever there was a write. So if you pile up drains faster than it can write the block you will get called after the first block was written, even if you wanted to be called after say block 5. Instead we track which block you wanted to be informed about and also keep track if the same block is written multiple times.
> Fix a bug where the waiting for drains pile up faster than we can write

- index.js
See https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map , we should use the methods `get`, `set`, `has`, `size`, etc.
Notice also that when there's high churn (high rate of `set` and `delete`), MDN link above says Map has better performance than Object.
:warning: I can't run the tests locally (not even in master), they fail for me, I don't know why. First time I ran it, they passed, second time they fail. Third time too. On the `basic.js` "basic json re-read" test.
> correct use of JS Map()

- README.md
- stream.js
- test/delete.js
- test/fix-buggy-write.js
- test/jacob.js
- test/stream.js
- test/stress-test.js
This is to make it fit better with jitdb and ssb-db2. See https://github.com/ssb-ngi-pointer/jitdb/issues/50.
> Rename seq to offset to match jitdb & ssb-db2

- index.js
- test/bad-offset.js
> Guard against NaN

- .gitignore
- package.json
This will help us know what still needs testing.
```
$ npm run coverage
```
```
-----------|---------|----------|---------|---------|--------------------------
File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s        
-----------|---------|----------|---------|---------|--------------------------
All files  |   93.71 |    85.23 |     100 |   94.59 |                          
compat.js |     100 |      100 |     100 |     100 |                          
index.js  |   94.71 |    89.16 |     100 |   96.32 | 213,259-260,284-287,304  
stream.js |   91.18 |    81.72 |     100 |   90.82 | 59,75-78,103,114,126-127 
-----------|---------|----------|---------|---------|--------------------------
```
> add nyc for test coverage

- index.js
- stream.js
- test/bench.js
- test/stream.js
It's faster and protects us early from type coercion bugs and tricky cases.
> replace double equals with triple equals

- stream.js
I bumped into these needs as I was trying to adopt `too-hot` in ssb-db2's log.js
> fix stream.js to allow pausing

- stream.js
- test/stream.js
> fix pause functionality

- .github/workflows/node.js.yml
- stream.js
- test/stream.js
> test case of live stream and pausing sink

- stream.js
The resume callback doesn't require closure scope, and I found using [0x](https://www.npmjs.com/package/0x) that moving this function reduces its time on the top of the stack while running JITDB benchmarks.
> Move function that does not use closure scope to be private member

- test/fix-concurrency-write-drain-bug.js
A little PR review in the form of another PR.
I made this test not "spam" the stdout, by putting the `for` loop inside the test. async-await was used just to make it possible to do a for-loop over the callbacks.
> refactor fix-concurrency-write-drain-bug test

- index.js
- test/fix-concurrency-write-drain-bug.js
First commit: test that fail :)
> Add test showing concurrency drain/write bug

- index.js
- stream.js
This PR changes a few minor internal things. I found these while reading the code again trying to find a bug related to corrupt [data](https://github.com/ssb-ngi-pointer/jitdb/issues/173):
- Strict use of let + const
- Consistent usage of === and !==
- Some names were changed to make the code easier to read and maintain
I have used this code to do a full sync in the browser. 
The PR can be read as the individual commits to better document what was changed.
> Code cleanup

- package.json
- test/stress-test.js
This is what I have been using to try and pin down bugs like https://github.com/ssb-ngi-pointer/ssb-db2/issues/302
> More stress testing

- test/bad-offset.js
- test/basic.js
- test/bench.js
- test/delete.js
- test/fix-buggy-write.js
- test/fix-concurrency-write-drain-bug.js
- test/idempotent-resume.js
- test/stream-pausable.js
- test/stream.js
- test/stress-test.js
Mostly just renaming variables, pretty conservative.
> rename variables in tests, for readability

- .prettierrc.yaml
- compat.js
- index.js
- package.json
- stream.js
- test/bad-offset.js
- test/basic.js
- test/bench.js
- test/bench2.js
- test/delete.js
- test/fix-buggy-write.js
- test/fix-concurrency-write-drain-bug.js
- test/idempotent-resume.js
- test/jacob.js
- test/stream-pausable.js
- test/stream.js
- test/stress-test.js
Adds prettier to package.json (same config as ssb-db2), and runs a script to format source code and tests. I didn't modify by hand any of the JS files in this PR.
> add prettier and automated scripts

- README.md
- index.js
Plus some tiny refactor on index.js, regarding opts defaults.
> add docs for API

- README.md
- index.js
Quick PR before I go for lunch
> code comment for internal API, and doc for since()

- test/delete.js
- test/fix-buggy-write.js
- test/stream-pausable.js
- test/stream.js
- test/stress-test.js
I'm actually working on #48, but I sometimes stumble upon refactors, so I'm branching them off early instead of accumulating them with the compaction PR.
> use push.collect instead of our own

- index.js
- stream.js
This PR is shaved off from another branch I have, I wanted to pick only the innocent refactors so that it's easier to review.
This PR just applies some renames for consistency and clarity. Things like:
- `buffer` renamed to `blockBuf` or `dataBuf` (depending on what the case is)
- `block` renamed to `blockBuf`
It's important to keep AAOL logic working well, so my PRs are going to be simple to make it easy spot problems.
> simple variable renaming, for consistency

- index.js
Stumbled upon a way to simplify this function. This is just a cosmetic refactor.
> refactor getLastGoodRecord to simplify it

- index.js
I'm gonna take a wild guess and assume that this PR fixes #86.
> fix and improve delete flushing
