ssbc/async-append-only-log

stream.js, test/stream.js
The newly added `tape('close')` test with the previous implementation was failing with:
```
/home/async-flumelog/stream.js:150
this.sink.end(err === true ? null : err)
^
TypeError: this.sink.end is not a function
at Stream.abort (/home/async-flumelog/stream.js:150:15)
at blocks.getBlock (/home/async-flumelog/stream.js:134:12)
at Object.getBlock (/home/async-flumelog/index.js:95:7)
at Stream._resume (/home/async-flumelog/stream.js:123:15)
at Stream._next (/home/async-flumelog/node_modules/.pnpm/looper@4.0.0/node_modules/looper/index.js:11:9)
at Stream.resume (/home/async-flumelog/stream.js:140:8)
at Stream.pipe (/home/async-flumelog/node_modules/.pnpm/push-stream@11.0.0/node_modules/push-stream/pipe.js:19:25)
at Test.<anonymous> (/home/async-flumelog/test/stream.js:95:29)
at Test.bound [as …
```
=> fix stream abort() when sink has no end()

README.md, index.js, package.json, test/jacob.js
This is an attempt to fix #11. As said in the issue I have looked over the code carefully and can't see where it should fail except if data becomes corrupt on write. Basically the log provided has 2 errors: corrupt bipf data and corrupt length information. Bipf has been super stable for me. I have never seen it fail to write data. And I tried to make async-flumelog as simple as possible, so that when it writes a record it literally just does buffer write of length + buffer copy of the actual data. Also considering this happened on 1 machine out of a bunch of manyverse machines makes me think this must be rather exceptional. We have run literally million of messages through this without any trouble.
What I *think* happened to jacobs log is that it became corrupt after about 300mb after …
=> Auto fix latest block if corrupted

stream.js, test/delete.js
Before when streaming we would just skip deleted values. The problem with this is that if you have offset based indexes like in jitdb, then the offsets won't match after you delete stuff if you compare an old index with a new one. And we don't want to reindex everything, so instead just stream deleted values as null and let the receiving end filter. It has to do that anyway in get.
=> Don't skip deleted data in stream

index.js
This should fix #15.
I think this can happen if you hit the write timeout. I'll try and see if I can get a test in to reproduce, but the fix should be simple enough. Would love an extra pair of eyes @staltz
=> Fix waiting drain already being deleted with multiple writes to the same block

stream.js, test/stream-pausable.js, test/stream.js
1st test, 2nd fix
**IF** the stream has many blocks **AND** the sink pauses frequently, **THEN** the previous implementation has a bug where it gets stuck at the last record, giving this last record over and over to the sink, in a loop.
The culprit was that `_handleBlock` needs 3 different return values, we can't signal "pause" on neither `true` nor `false` (I tried many times, all sorts of tricks).
=> fix stream.js to allow pausing when there are many blocks

index.js
When reading through async-append-only-log trying to figure out the seeming lack of atomicity in its writes, I ran across this rather strangely-used `for` loop.  This refactors it into an `if` for clarity.  Seems to be about equivalent for performance, possibly slightly faster although by a fairly insignificant margin.
=> Refactor for loop to if

index.js, package.json
These 2 commits should make writes safer in general.
- Fsync: this is similar to what we use in [atomic-file-rw](https://github.com/ssb-ngi-pointer/atomic-file-rw/blob/379458da1d988b75038e2e93acd689a7df3b0935/fs.js#L34)
- Locking: also a technique also used in [atomic-file-rw](https://github.com/ssb-ngi-pointer/atomic-file-rw/blob/379458da1d988b75038e2e93acd689a7df3b0935/fs.js#L24)
It is worth mentioning that the locking actually fixes a potential (rare) problem. The following could happen: 
- we schedule a write for block 100 which is not full
- The scheduled write happens, while it is writing (async operation) we add something more to the block 100
- Before it finishes the write, the second write is scheduled to run, which leads to 2 concurrent writes to the same part of the file, which …
=> Safer writes

index.js, test/basic.js
This adds the ability to make sure that several pieces of data are written to disc at the same time. We need this support for indexed replication in EBT where you will receive both the index + the indexed message at the same time and need to make sure that we write the messages to disc in one go so that local db2 indexes will see the messages at the same time and also that EBT can expect that if it sees an index that the indexed message will be there. Lastly if it crashes in the middle, that we can use the index to know that we for sure will also have the indexed message stored. Basically we need to add things in what amounts to a transaction :-)
=> Transaction support

stream.js, test/idempotent-resume.js
Full context for this PR is given at the comment https://github.com/ssb-ngi-pointer/ssb-db2/issues/302#issuecomment-1015534847. This PR is fundamental to fix several database glitches experienced by users of ssb-db2.
1st :x:, 2nd :heavy_check_mark:
=> fix stream.resume() to be idempotent

stream.js, test/stream.js
First test should reproduce the bug seen in [replication scheduler](https://github.com/ssb-ngi-pointer/ssb-replication-scheduler/pull/5#issuecomment-1043197983)
The problem was that it was possible to set skip_next on an empty database so that the first value is actually skipped and never returned to the indexes.
=> Add test for ending up in wrong skip_next state on empty db

index.js
Something I stumbled upon while working on compaction, is that we should use `Buffer.fill()` instead of allocating a new buffer and copying over. But also it's good to discover this now, before we start making extensive usage of del().
Use this script in Node.js to verify the numbers yourself:
```js
const TOTAL_SIZE = 100e6 // 100 MB
const FILL_SIZE = 10
const TIMES = TOTAL_SIZE / FILL_SIZE
const buf1 = Buffer.allocUnsafe(TOTAL_SIZE)
const buf2 = Buffer.allocUnsafe(TOTAL_SIZE)
console.time('copy')
for (let i = 0; i < TIMES; i++) {
const start = FILL_SIZE * i
const end = FILL_SIZE * (i + 1)
Buffer.alloc(FILL_SIZE).copy(buf1, start)
}
console.timeEnd('copy')
console.time('fill')
for (let i = 0; i < TIMES; i++) {
const start = FILL_SIZE * i
const end = FILL_SIZE * (i + 1)
buf2.fill(0, start, …
```
=> improve del() performance by 2x

index.js, record.js
This is my last PR for today. 
My motivation is that I was stumbling upon all these `+ 2` in the offset math, and felt that this stuff is easy to get wrong, so I moved all of that logic to its own file, `./record.js` which is the only place that knows about `uint16`. This makes it easier in the future, in case we want to upgrade to `uint32` (or whatever), we only have a small file to update. The goal was to separate the "internals of a record" from the overall logic of a "block".
Additional stuff: 
- made end-of-block logic more explicit
- Some reordering of lines to maintain consistency
- Changing a `array.forEach` to `for (const x of array)` because it's better for stack traces
=> move record byte math to its own file

index.js, stream.js, test/basic.js, test/fix-buggy-write.js, test/fix-concurrency-write-drain-bug.js, test/jacob.js
I'm already working on compaction (PR #55), but I noticed this: we have both `onReady` and `onLoad`, which do basically the same thing. Also, `onLoad` only supported functions with two arguments: `(input, cb) =>` so it would not work in case we added another API with 3 or more arguments. This PR changes that.
=> refactor onLoad

index.js, package.json
Fixes #59 
I ran the benchmarks in jitdb with this and it appears we have the same numbers in the normal case. The microbenchmarks confirms this: https://github.com/arj03/is-buffer-zero
=> Use is-buffer-zero to check for deleted records

index.js
A side quest for PR #55:
- [refactor: simplify write() versus writeBlock()](https://github.com/ssb-ngi-pointer/async-append-only-log/commit/e58f31563bcfe2b9dddb68a5bafad118b3fd9f22)
- I took a look at these two functions many times, and it seems like we only need one function, so I deleted the other
- [refactor: give names to functions to improve debuggability](https://github.com/ssb-ngi-pointer/async-append-only-log/commit/32c461bfcf8bbc6a822cb3e57c004211ea62be64)
- Avoiding anonymous functions, because they're not great for stack traces from production
=> Refactor function names in index.js

errors.js, index.js, test/bad-offset.js, test/delete.js
- [throw errors, not strings, from log.get](https://github.com/ssb-ngi-pointer/async-append-only-log/commit/6f459d1ee840e8deb054b6e5d362ad4d72990158)
- [throw error if log.get has too large offset](https://github.com/ssb-ngi-pointer/async-append-only-log/commit/832f54c0878da3906a96cf8d430e64e8e425ef76)
- This is a bit more relevant now for truncated logs after compact is done, because it's possible that the consumer code has references to outdated offsets
- [use err.code for log.get errors](https://github.com/ssb-ngi-pointer/async-append-only-log/pull/64/commits/3d24638e7d3b69eeba5a867ad93928a4bff95950)
- `ERR_AAOL_OFFSET_OUT_OF_BOUNDS` is going to be useful for jitdb and ssb-db2, I think
- [refactor log.get internals](https://github.com/ssb-ngi-pointer/async-append-only-log/pull/64/commit …
=> Revisit errors thrown from log.get

index.js
I'm trying to address "*What about concurrent del and append on the same block?*" from PR #55, and I realized that we only need to protect `del()` happening on the latest block, because no writes can be done to previous blocks anyway.
I am actually not sure if this PR is the right way. One question that came to mind: if you do a `del()` and an `onDrain(cb)`, then the onDrain's `cb` should let you read blocks where the state is "updated" with the delete, right? So technically `onDrain()` should wait for the `del()` to happen. But that's not currently happening.
=> protect del() from concurrency on the latest block

README.md, compaction.js, errors.js, index.js, package.json, test/basic.js, test/compaction.js
Things to be reviewed:
- Are we really okay with not protecting `log.get` and `log.stream` being called during compaction?
- What should we do with `log.since` once compaction is done? Set it to the new latest offset? And how will ssb-db2 react when the log.since is now smaller?
=> Compaction

README.md, index.js, test/compaction.js, test/delete.js
For issue https://github.com/ssb-ngi-pointer/ssb-db2/issues/334
@arj03 I don't think this PR is ready but I want to ask you a couple questions.
I'm using a batching strategy similar to `scheduleWrite` for the deletes. The results are pretty nice:
**Before:**
```
append 1000 records: 125.351ms
delete 1000 records: 897.869ms
```
**After:**
```
append 1000 records: 107.628ms
delete 1000 records: 19.421ms
```
I suspect it got faster than append because deletes use `buffer.fill` while appends use `buffer.copy`.
Issues:
- I added the new API `onFlushDelete` which is like `onDrain` but for deletes. I don't think this is great, I would have wanted that `onDrain` also waits for deletes to end, but it's tricky because `onDrain` just adds CBs to the `latestBlockIndex`, but deletes can happen on any …
=> speed up deletes and add onDeletesFlushed()

compaction.js, test/compaction.js
After the compaction state file is destroyed, but *before* log.truncate is done, the program could crash. And then, when restarting the program, it wouldn't find any state file and would not auto-restart the compaction algorithm, leaving the log un-truncated and no space would be freed up.
```js
function stop() {
compactedBlockBuf = null
unshiftedBlockBuf = null
persistentState.destroy(function onCompactionStateDestroyed(err) {
if (err) return onDone(err)
// CRASH AT THIS POINT <----
log.truncate(compactedBlockIndex, onDone)
})
}
```
Save also `truncateBlockIndex` in the state file so we handle these kinds of crashes.
Also introduces a `version` field in the state file. Technically this PR introduces the **2nd** file format version, but I believe no one used compaction in production, so …
=> Crash before truncate

compaction.js, index.js, test/compaction.js
Other libraries like jitdb and ssb-db2 need to know whether compaction is happening or not (as a boolean). But in `master` branch, if there was no compaction yet, then `compactionProgress` would emit nothing and those libraries would not have a sure way of knowing that it's not happening yet.
When restarting compaction from a crash, the `startOffset` emitted in `compactionProgress` has to be the same value as it would have been if compaction had just started, because the `startOffset` is important to know where the jitdb reindexing should start from.
`startOffset` is saved in the compaction state file, and when AAOL is init'ed, it immediately emits an event on `compactionProgress` so that other libraries can read `compactionProgress.value` and know whether there's something ongoing or …
=> first compactionProgress events should have startOffset

compaction.js, index.js, test/compaction.js
Context: https://github.com/ssb-ngi-pointer/jitdb/issues/199
In my ssb-db2 PR https://github.com/ssb-ngi-pointer/ssb-db2/pull/339, I had a `if (sizeDiff > 0) resetIndexes()` but this misses a corner case. `sizeDiff` is only greater than zero if truncation removed at least one block. But `sizeDiff === 0` can mean two very different things:
- Compaction found no holes at all, and the log does not need compaction, it's left intact
- Compaction found holes but only a few, and performed "shifting" of records to rewrite the log, but the total size remained the same
We need to rebuild indexes in the 2nd case, but not in the 1st. So we need a way of knowing the difference between these cases.
Use `sizeDiff === 1` as a special case where no blocks have been truncated (the log size remained the …
=> use sizeDiff=1 to represent holes filled

index.js, package.json
Background:
This [PR](https://github.com/dominictarr/hashlru/pull/21) lead me to [quick-lru](https://www.npmjs.com/package/quick-lru) which sadly is ESM. But they still maintain an older version: https://github.com/sindresorhus/quick-lru/releases/tag/v6.0.0.
This PR:
Replace hashlru with quick-lru that uses a map internally. I tried benchmarking this but couldn't see a big difference. One area where this might help is in compaction.
=> Switch from hashlru to quick-lru

index.js, test/compaction.js
Using `compactionProgress` in the UI is not good, because for each record shifted/compacted, it updates, which means it's spamming the frontend a lot. We should do something smarter, like ssb-db2 `status` does.
Throttle the progress updates such that they are not "closer" than 1 second to each other. The exceptions are: the first `done = false` update is always emitted (this is important so the UI knows that compaction has started), and any `done = true` update is always emitted.
1st :x: 2nd :heavy_check_mark:
=> throttle compactionProgress with 1sec

README.md, index.js, stream.js, test/compaction.js, test/idempotent-resume.js, test/stream-pausable.js, test/stream.js
Manyverse will need to know how much space _would_ be saved by compaction *before* kickstarting compaction. We don't want the user to reindex leveldb in vain if there are just a handful of deleted records.
There is no way of knowing, with the current API, such information, without actually running compaction.
`log.stats()` is a new API that does a scan on the log (and this is implemented in AAOL and not in ssb-db2 so to avoid the extra log scan logic it has such as `decrypt`), counting how many deleted records there are and how much space in total those deleted records occupy. This would then be bubbled up to the UI, to the user, so the user can make an informed decision when to compact.
`log.stream(opts)` now also supports `opts.sizes`, to achieve the above.
I also changed `log.streams` …
=> new API log.stats()

compaction.js, test/compaction.js
Context: https://github.com/ssbc/jitdb/pull/221
Important note: `holesFound` does not count holes from the *previous* compaction run (assume there was a crash + resume), i.e. the counter is not kept in the state file. The good news is that we don't need the counter in the state file because there are no jitdb queries that keep state before and after an app crash ( https://github.com/ssbc/jitdb/pull/221 ).
=> include holesFound in compactionProgress stats

compaction.js, stream.js, test/stream.js
[jitdb uses `push.drain()` to scan the log](https://github.com/ssbc/jitdb/blob/b17fa8bbd0520368a08ae0e3651b3ccd88674ae7/index.js#L1292-L1311), and to my surprise, after the `return false` to abort the sink, the sink still kept receiving new records!
When using an AAOL push-stream with `push.drain()` from the `push-stream` toolkit, if you `return false` to abort the sink, then the push-stream source *keeps feeding you values*. See new test added.
At first I thought that push-stream `push.drain()` is wrong, and maybe it still is, because push-stream is a somewhat incomplete project. For instance, what's the difference between `this.paused` and `this.ended`? Do only sources have `this.ended`? (This is complicated by the fact that some objects are BOTH push-stream source and push-stream sink) …
=> log.stream to support push.drain()

README.md, index.js, package.json, test/compaction.js
Scanning the log is slow, some ~5 seconds on desktop and more on mobile.
I use `log.stats` to show charts on the new Manyverse Storage screen, and this means a 5 second delay to open that screen, waiting for the scan to end.
The most important metric is `deletedBytes`, (because `totalBytes` is just `since.value` and the `totalCount` and `deletedCount` were never used yet by any other code), which can be persisted and incremented every time a delete occurs.
There's now an atomic file `log.bipf.stats` with stringified JSON to hold these stats, which at the moment is just `{ deletedBytes }`. This is much faster than scanning, but there is a slight chance that the calculation goes wrong if the stats file is deleted or corrupted.
Technically, removing `totalCount` and `deletedCount` is a …
=> avoid scanning the log for log.stats()

index.js, test/compaction.js
**Problem:** `stats()` returns `totalBytes === -1` if the log has not yet been written to.
**Solution:** `since.value` at `-1` makes sense for internal programming, but here we want to measure only the number of bytes, so we cap the lowest value to be zero.
1st :x: 2nd :heavy_check_mark:
=> stats() smallest totalBytes should be zero

errors.js, index.js, stream.js, test/compaction.js
https://github.com/ssbc/ssb-replication-scheduler/issues/3
Compaction waits for non-live streams to complete before applying the algorithm, but **live** streams remain as is, and they have a `cursor` which often points to the latest record at a very high offset. After compaction is done, the highest offset is smaller because the log got smaller, but the live stream cursor is greater than that. This may cause EPARTIALREAD errors with RAF.
When compaction is done, it "resets" all live streams by setting their cursor to `since.value`. This assumes a lot of things and may be dangerous in the future. To name these assumptions:
- We assume that all live streams have caught up with log
- We assume that no live stream uses `opts.lt` or `opts.lte`
- We assume that no live streams were set with …
=> fix live stream post-compaction

README.md, index.js
Right now this module no longer works in the browser. The main reason is the `fsSync` call in `stateFileExists` on start. Tried to make these changes as minimal as possible. Can confirm that with this and a minor fix in ssb-db2 that ssb-browser-core is working again with latest db2.
=> Compaction disable browser

index.js
Sorry, there was one more :cry: 
I did some more testing of browser-core and this was the last one missing, it was just a warning anyway nice to get removed.
=> Don't try to resume compaction in browser
